Fix method definition parsing for strings in keyword args
ruby/prism pull request #1578
Opened 2023-09-21 14:31 UTC by haldun

Closes #1572

Also fixed other modifiers (what are those '%x', '%w' called in Ruby?) in the keyword args like:

```ruby
def foo x:%w(xx); end
```

2023-09-28 09:36 UTC, haldun commented
Rebased with main.

2023-11-09 05:49 UTC, kddnewton requested changes

2023-11-09 05:49 UTC, kddnewton commented on src/prism.c
> +                        parser->in_keyword_arg
I have the same issue here that I have in the other one in that this doesn't match up to `parse.y`. I think if we fix the other one this one will probably be fixed as well.

2023-11-13 08:59 UTC, haldun commented
Closing in favor of #1591

2023-11-13 08:59 UTC, closed without merging