Fix segfault for invalid `frozen_string_literals` magic comment
ruby/prism pull request #1630
Opened 2023-10-05 18:45 UTC by andyw8

Closes https://github.com/ruby/prism/issues/1629

2023-10-05 18:47 UTC, andyw8 commented
(wrong commit, will fix)

2023-10-05 19:02 UTC, andyw8 commented on src/prism.c
>          if (memcmp(cursor, "frozen_string_literal", key_length) == 0) {
This is passing but I'm unsure if the other references to `key_length` are still correct.

2023-10-05 19:04 UTC, andyw8 commented on src/prism.c
>          if (memcmp(cursor, "frozen_string_literal", key_length) == 0) {
Ah, it passed locally but I'm seeing CI failures.

2023-10-05 22:48 UTC, kddnewton requested changes
Unfortunately you can have space between frozen_string_literal and : so this won't quite work as expected

2023-10-13 19:12 UTC, kddnewton commented
Fixed by #1685

2023-10-13 19:12 UTC, closed without merging