Implement JavaScript visitors
ruby/prism pull request #1769
Opened 2023-11-04 22:31 UTC by marcoroth

This pull request adds a new template for a `visitor.js` file in `javascript/src/`. This file implements a `BasicVisitor` and a `Visitor` class, very similar to the Ruby visitors which allow to traverse the Ruby AST in JavaScript.

An example of a custom `FooCalls` visitor in JavaScript would look like:

```js
import { loadPrism, Visitor } from "@ruby/prism"

class FooCalls extends Visitor {
  visitCallNode(node) {
    if (node.name === "foo") {
      // Do something with the node
    }

    // Call super so that the visitor continues walking the tree
    super.visitCallNode(node);
  }
}

const fooVisitor = new FooCalls()
const parse = await loadPrism()
const parseResult = parse("foo()")

parseResult.value.accept(fooVisitor)
```

2023-11-09 05:19 UTC, kddnewton requested changes
Looks good! Added a couple of minor comments.

2023-11-09 05:19 UTC, kddnewton commented on docs/javascript.md
> +const parseResult = parse("foo()")
```suggestion
const parse = await loadPrism();
const parseResult = parse("foo()");
```

2023-11-09 05:19 UTC, kddnewton commented on docs/javascript.md
> +parseResult.value.accept(fooVisitor)
```suggestion
const fooVisitor = new FooCalls();

parseResult.value.accept(fooVisitor);
```

2023-11-09 05:19 UTC, kddnewton commented on javascript/README.md
> +See the [JavaScript documentation](../docs/javascript.md) for Prism.
This isn't going to get shipped with the package, so the link is going to be broken for npm/node_modules. So maybe link absolutely? Like https://github.com/ruby/prism/blob/main/docs/javascript.md maybe?

2023-11-09 05:19 UTC, kddnewton commented on templates/javascript/src/nodes.js.erb
> +   * @returns {Node[]} An array of child nodes.
```suggestion
   * @returns {(Node | null)[]} An array of child nodes.
```

2023-11-09 05:19 UTC, kddnewton commented on templates/javascript/src/nodes.js.erb
> +    const compact = []
```suggestion
    const compact = [];
```

2023-11-09 05:19 UTC, kddnewton commented on templates/javascript/src/nodes.js.erb
> +    compact.push(this.<%= prop(field) %>)
```suggestion
    compact.push(this.<%= prop(field) %>);
```

2023-11-09 05:19 UTC, kddnewton commented on templates/javascript/src/nodes.js.erb
> +      compact.push(this.<%= prop(field) %>)
```suggestion
      compact.push(this.<%= prop(field) %>);
```

2023-11-09 05:19 UTC, kddnewton commented on templates/javascript/src/nodes.js.erb
> +    compact.concat(this.<%= prop(field) %>)
```suggestion
    compact.concat(this.<%= prop(field) %>);
```

2023-11-09 05:19 UTC, kddnewton commented on templates/javascript/src/nodes.js.erb
> +    return compact
```suggestion
    return compact;
```

2023-11-09 05:19 UTC, kddnewton commented on templates/javascript/src/nodes.js.erb
> +    }.compact.join(", ") %>]
```suggestion
    }.compact.join(", ") %>];
```

2023-11-10 17:44 UTC, marcoroth commented
Thanks for the review, I address all the points 👍🏼 

Does it make sense to introduce a formatter/linter for theJavaScript files as well?

2023-11-11 22:00 UTC, kddnewton approved these changes
At some point yeah, it probably makes sense to that. But for now I'm really enjoying there not being any dependencies at all - even for build.

2023-11-11 22:00 UTC, merged