Add and test ibm863 encoding
ruby/prism pull request #1853
Opened 2023-11-17 02:21 UTC by wildmaples

ibm863 is also known as cp863

https://github.com/ruby/prism/issues/1843

2023-11-17 11:00 UTC, eregon commented
Given CP863 is just an alias of IBM863 it would be best to avoid duplicating the table, especially since there are lots of aliases (Encoding.aliases.size => 71).
```
irb(main):005:0> Encoding::CP863
=> #<Encoding:IBM863>
```

I guess what we need is a function that resolves aliases names to the canonical encoding name, the same way `Encoding.aliases[name]` can do it.

2023-11-17 14:56 UTC, kddnewton requested changes

2023-11-17 14:56 UTC, kddnewton commented on bin/encodings
> +when "cp863"       then table(Encoding::CP863)
Typically we're only putting the main constants in here, and since `Encoding::CP863` is an alias of `Encoding::IBM863`, we don't need it here.

2023-11-17 14:56 UTC, kddnewton commented on include/prism/enc/pm_encoding.h
> +extern pm_encoding_t pm_encoding_cp863;
Same comment here, we only need the one constant.

2023-11-17 14:56 UTC, kddnewton commented on src/prism.c
> +                ENCODING1("CP863", pm_encoding_ibm862);
```suggestion
```

2023-11-17 14:56 UTC, kddnewton commented on test/prism/encoding_test.rb
> +      Encoding::CP863 =>        0x00...0x100,
```suggestion
```

2023-11-17 14:56 UTC, kddnewton commented on src/enc/pm_tables.c
> +
```suggestion
```

2023-11-17 14:56 UTC, kddnewton commented on src/enc/pm_tables.c
> +PRISM_ENCODING_TABLE(cp863)
```suggestion
```

2023-11-17 14:56 UTC, kddnewton commented on src/enc/pm_tables.c
> +
```suggestion
```

2023-11-17 14:56 UTC, kddnewton commented on src/enc/pm_tables.c
> +
```suggestion
```

2023-11-20 18:56 UTC, kddnewton approved these changes
Looks great!

2023-11-20 19:09 UTC, kddnewton commented
Nice! This works just needs a rebase

2023-11-20 19:44 UTC, kddnewton commented on src/enc/pm_tables.c
> +PRISM_ENCODING_TABLE(ibm863)
Whoops now we're just missing the `ibm863` table. If you generate it with `bin/encodings ibm863` you should be able to copy-paste.

2023-11-20 20:05 UTC, kddnewton approved these changes

2023-11-20 20:05 UTC, merged