Fix to parse command-style method calls more correctly
ruby/prism pull request #1949
Opened 2023-11-30 08:55 UTC by makenowjust

Fix #1468
Fix #1575

To decide whether command-style method calls are allowed, this introduces a new parameter `accepts_command_call` to `parse_expression` and some functions.

Although one thinks this can be solved by operator precedence, it is hard or impossible, because the precedence of command-style calls is skewed (e.g. `! bar 1 ` is accepted, but `foo = ! bar 1` is rejected.)

One of the most complex examples is that:

1. even though `foo = bar = baz 1` and `foo, bar = baz 1` is accepted,
2. `foo, bar = baz = fuzz 1` is rejected.

To implement this behavior, this introduces a new binding power `PM_BINDING_POWER_MULTI_ASSIGNMENT` and uses it to distinguish which single assignments or multi assignments at their RHS.

2023-11-30 14:23 UTC, kddnewton requested changes
Amazing work @makenowjust! I have a couple of small-ish requests, but otherwise this looks really, really good.

2023-11-30 16:36 UTC, makenowjust commented on src/prism.c
>          case PM_TOKEN_KEYWORD_AND: {
I like my version because your suggestion is not clear what is different between them at first glance.

2023-11-30 16:37 UTC, makenowjust commented on src/prism.c
> +parse_expression(pm_parser_t *parser, pm_binding_power_t binding_power, pm_diagnostic_id_t diag_id, bool accepts_comamnd_call);
Okay. But, it is really boring task.

2023-11-30 17:31 UTC, makenowjust commented on src/prism.c
> +            // A command-style method call is only accepted on method chains.
I try to implement it.

2023-12-01 07:34 UTC, makenowjust commented on src/prism.c
> +            // A command-style method call is only accepted on method chains.
@kddnewton 

It has not yet been implemented for two reasons.

1. I am not sure that this optimization is effective. In the first place, it is also unclear whether the current implementation has any impact on performance.
2. The `METHOD_CHAIN` flag seems abusing of flags. This flag is used for parsing purposes and has no benefit to the user. I have concerns about such a flag to be exposed to users.

At least the current implementation works correctly. Optimization could be done after the merge.

2023-12-01 21:03 UTC, haldun commented on src/prism.c
> +parse_expression(pm_parser_t *parser, pm_binding_power_t binding_power, bool accepts_comamnd_call, pm_diagnostic_id_t diag_id);
There is a typo in the argument name.

2023-12-05 03:18 UTC, kddnewton commented on src/prism.c
> +            // A command-style method call is only accepted on method chains.
@makenowjust I agree. Let's do optimizations later. If you don't mind rebasing, I will merge this.

2023-12-05 04:59 UTC, makenowjust commented
Rebasing is done.

2023-12-05 14:22 UTC, froydnj commented on src/prism.c
> +            // A command-style method call is only accepted on method chains.
FWIW, a method chain flag would be useful to e.g. `rubyfmt` so it wouldn't have to recompute that information.

2023-12-05 14:36 UTC, makenowjust commented on src/prism.c
> +            // A command-style method call is only accepted on method chains.
@froydnj Perhaps this flag is not what you expected. This flag should be named `POSSIBLY_A_PART_OF_METHOD_CHAIN_FOR_OPTIMIZING_TO_PARSE_COMMAND_STYLE_METHOD_CORRECTLY`, and it is used only for the parsing purpose (not for users).

2023-12-05 15:16 UTC, kddnewton approved these changes

2023-12-05 15:16 UTC, merged