Add a `PM_KEYWORD_HASH_NODE_FLAGS_STATIC_LITERAL_ASSOC_NODE_KEYS` flag for `KeywordHashNode`s
ruby/prism pull request #2046
Opened 2023-12-11 20:35 UTC by paracycle

The CRuby compiler changes how it handles keyword hashes depending on if:
1. All elements are `AssocNode`s with static literal keys, in which case these can be sent to the call as keyword arguments,
2. Otherwise, the elements need to be collected in a hash and sent as an extra positional argument.

https://github.com/ruby/ruby/pull/9147 implements that behaviour inside CRuby by looping over the elements of `KeywordHashNode` to detect either of these cases, but a better way to do that is to add a flag to `KeywordHashNode` to keep this state.

This PR implements that feature by making all `KeywordHashNode` elements start off with the `PM_KEYWORD_HASH_NODE_FLAGS_STATIC_LITERAL_ASSOC_NODE_KEYS` flag set. When an element is added to the keyword hash node, we check if the element is an `AssocNode` and if its key is a static literal. If we fail either of those conditions, then we clear the flag on the keyword hash node.

Ref: https://github.com/ruby/ruby/pull/9147#discussion_r1421126156

2023-12-11 20:45 UTC, kddnewton requested changes

2023-12-11 21:00 UTC, paracycle commented on config.yml
> +      - name: STATIC_LITERAL_ASSOC_NODE_KEYS
Changed!

2023-12-12 13:04 UTC, kddnewton approved these changes
Nice work!

2023-12-12 13:05 UTC, merged

2023-12-13 13:21 UTC, eregon commented
Is the CRuby optimization done for any static key (e.g. for `foo(nil => value)`) or only for literal symbol keys?

2023-12-14 09:43 UTC, eregon commented
https://github.com/ruby/prism/pull/2069 so it's only literal symbol keys.