Document `ConstantPathNode` fields
ruby/prism pull request #2140
Opened 2024-01-08 22:38 UTC by matthew-healy

This PR updates `config.yml` to add documentation for the fields of `ConstantPathNode`.

2024-01-08 22:42 UTC, matthew-healy commented on config.yml
> +          The right-hand node of the path. Always a `ConstantReadNode`.
The [Advent of Prism section](https://kddnewton.com/2023/12/03/advent-of-prism-part-3.html#constantpathnode) states that `child` is "almost always a constant read". 

Looking at the calls to `pm_constant_path_node_create` in `src/prism.c`, they're all passed the result of `pm_constant_read_node_create`, with the exception of [this one](https://github.com/ruby/prism/blob/a81b4ce9cbeda7118461beb78d10564c11c6319b/src/prism.c#L17020) which is passed a `MissingNode` & results in an error.

2024-01-17 20:35 UTC, matthew-healy commented
Not sure why the C documentation generation is failing - I can run `doxygen Doxyfile` fine locally. Is that check known to be flaky? :thinking:

2024-01-17 20:39 UTC, kddnewton commented
Nope, not flaky. Looks like there's a warning about `Foo` in the output of doxygen in the test run

2024-01-17 21:13 UTC, matthew-healy commented
The issue was that doxygen read the `::Foo` in the comment as a reference to part of the C codebase, which it then couldn't find. Have just removed that part of the comment. 

(I couldn't repro it locally initially because I'd forgotten to run `bundle exec rake templates` :sweat_smile:).

2024-03-11 13:48 UTC, kddnewton requested changes

2024-03-11 13:48 UTC, kddnewton commented on config.yml
> +          lookup is at the root of the module tree.
```suggestion
          The left-hand node of the path, if present. Can be `nil` or any kind of a node returning a non-void value. Will be`nil` when the constant lookup is at the root of the module tree.
```

2024-03-11 13:48 UTC, kddnewton approved these changes

2024-03-11 19:45 UTC, kddnewton requested changes

2024-03-11 19:45 UTC, kddnewton commented on config.yml
> +          The left-hand node of the path, if present. Can be `nil` or any kind of a node returning a non-void value. Will be`nil` when the constant lookup is at the root of the module tree.
```suggestion
          The left-hand node of the path, if present. Can be `nil` or any kind of a node returning a non-void value. Will be `nil` when the constant lookup is at the root of the module tree.
```

2024-04-23 14:52 UTC, merged