GitHub Action that uploads builds as release artifacts
ruby/prism pull request #3272
Opened 2024-12-02 22:20 UTC by egiurleo

This GitHub Action builds Prism for Linux and MacOS and then uploads the builds to the latest release to be used by clients such as Sorbet

2024-12-03 01:27 UTC, kddnewton requested changes
One quick change, looks great!

2024-12-03 01:27 UTC, kddnewton commented on .github/workflows/build-artifacts.yml
> +        ruby-version: '3.2'
Can we make this 3.3?

2024-12-03 19:32 UTC, tenderlove approved these changes

2024-12-04 14:44 UTC, kddnewton approved these changes

2024-12-04 14:44 UTC, merged